language: node_js
node_js:
- "5"
sudo: false
script:
  - npm run build
  - npm run cover
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
  - "CODECLIMATE_REPO_TOKEN=e4d23290bb8b191fc1984aa9e0fe9af4d1b0e645a5f9b398264bb68a3df39c5d  node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage/lcov.info"
